@host = localhost:8080

// Create Product
POST http://{{host}}/blockchain HTTP/1.1
content-type: application/json
    
{
    "address": "maick"
}

###

// Get Product By ID
GET http://{{host}}/api/pokemons/158 HTTP/1.1
content-type: application/json

###

// Get All Products
GET http://{{host}}/blockchain HTTP/1.1
content-type: application/json

###

// Update Product
POST http://{{host}}/blockchain/transactions HTTP/1.1
content-type: application/json

{
    "from": "maick",
    "to": "jean",
    "amount": 80
}

###

// Delete Product
DELETE http://{{host}}/api/pokemons/1 HTTP/1.1
content-type: application/json
